[2025-06-18 16:16:51,342] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: connect_postgres_dag.create_postgres_table 2022-07-09T00:00:00+00:00 [queued]>
[2025-06-18 16:16:51,374] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: connect_postgres_dag.create_postgres_table 2022-07-09T00:00:00+00:00 [queued]>
[2025-06-18 16:16:51,374] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2025-06-18 16:16:51,375] {taskinstance.py:1043} INFO - Starting attempt 1 of 6
[2025-06-18 16:16:51,375] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2025-06-18 16:16:51,411] {taskinstance.py:1063} INFO - Executing <Task(PostgresOperator): create_postgres_table> on 2022-07-09T00:00:00+00:00
[2025-06-18 16:16:51,419] {standard_task_runner.py:52} INFO - Started process 27616 to run task
[2025-06-18 16:16:51,427] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'connect_postgres_dag', 'create_postgres_table', '2022-07-09T00:00:00+00:00', '--job-id', '14330', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/connect_postgres_dag.py', '--cfg-path', '/tmp/tmpo1_98eq5', '--error-file', '/tmp/tmpfyv8mn9x']
[2025-06-18 16:16:51,430] {standard_task_runner.py:77} INFO - Job 14330: Subtask create_postgres_table
[2025-06-18 16:16:51,552] {logging_mixin.py:104} INFO - Running <TaskInstance: connect_postgres_dag.create_postgres_table 2022-07-09T00:00:00+00:00 [running]> on host 500dc4ac3a72
[2025-06-18 16:16:51,693] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=coder2j
AIRFLOW_CTX_DAG_ID=connect_postgres_dag
AIRFLOW_CTX_TASK_ID=create_postgres_table
AIRFLOW_CTX_EXECUTION_DATE=2022-07-09T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-07-09T00:00:00+00:00
[2025-06-18 16:16:51,694] {postgres.py:69} INFO - Executing: 
            create table if not exists employee (
                "name" text,
                "age" integer,
                "salary" numeric
            )
        
[2025-06-18 16:16:51,709] {base.py:74} INFO - Using connection to: id: postgres_localhost. Host: postgres, Port: 5432, Schema: test, Login: airflow, Password: XXXXXXXX, extra: None
[2025-06-18 16:16:51,719] {dbapi.py:180} INFO - Running statement: 
            create table if not exists employee (
                "name" text,
                "age" integer,
                "salary" numeric
            )
        , parameters: None
[2025-06-18 16:16:51,721] {dbapi.py:186} INFO - Rows affected: -1
[2025-06-18 16:16:51,721] {postgres.py:73} INFO - NOTICE:  relation "employee" already exists, skipping

[2025-06-18 16:16:51,752] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=connect_postgres_dag, task_id=create_postgres_table, execution_date=20220709T000000, start_date=20250618T161651, end_date=20250618T161651
[2025-06-18 16:16:51,859] {taskinstance.py:1220} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-06-18 16:16:51,894] {local_task_job.py:146} INFO - Task exited with return code 0
