[2025-06-18 14:59:54,137] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: first_dag.third_task 2021-08-01T00:00:00+00:00 [queued]>
[2025-06-18 14:59:54,160] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: first_dag.third_task 2021-08-01T00:00:00+00:00 [queued]>
[2025-06-18 14:59:54,160] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2025-06-18 14:59:54,160] {taskinstance.py:1043} INFO - Starting attempt 2 of 6
[2025-06-18 14:59:54,161] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2025-06-18 14:59:54,189] {taskinstance.py:1063} INFO - Executing <Task(BashOperator): third_task> on 2021-08-01T00:00:00+00:00
[2025-06-18 14:59:54,195] {standard_task_runner.py:52} INFO - Started process 3133 to run task
[2025-06-18 14:59:54,203] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'first_dag', 'third_task', '2021-08-01T00:00:00+00:00', '--job-id', '9705', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmptxdiygrg', '--error-file', '/tmp/tmprmlk4vbb']
[2025-06-18 14:59:54,206] {standard_task_runner.py:77} INFO - Job 9705: Subtask third_task
[2025-06-18 14:59:54,293] {logging_mixin.py:104} INFO - Running <TaskInstance: first_dag.third_task 2021-08-01T00:00:00+00:00 [running]> on host 500dc4ac3a72
[2025-06-18 14:59:54,366] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=coder2j
AIRFLOW_CTX_DAG_ID=first_dag
AIRFLOW_CTX_TASK_ID=third_task
AIRFLOW_CTX_EXECUTION_DATE=2021-08-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-08-01T00:00:00+00:00
[2025-06-18 14:59:54,367] {bash.py:135} INFO - Tmp dir root location: 
 /tmp
[2025-06-18 14:59:54,369] {bash.py:158} INFO - Running command: echo "this is third task "
[2025-06-18 14:59:54,381] {bash.py:169} INFO - Output:
[2025-06-18 14:59:54,382] {bash.py:173} INFO - this is third task
[2025-06-18 14:59:54,383] {bash.py:177} INFO - Command exited with return code 0
[2025-06-18 14:59:54,430] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=first_dag, task_id=third_task, execution_date=20210801T000000, start_date=20250618T145954, end_date=20250618T145954
[2025-06-18 14:59:54,471] {taskinstance.py:1220} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-18 14:59:54,493] {local_task_job.py:146} INFO - Task exited with return code 0
