[2025-06-18 16:15:51,061] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: connect_postgres_dag.insert_into_table 2021-12-22T00:00:00+00:00 [queued]>
[2025-06-18 16:15:51,075] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: connect_postgres_dag.insert_into_table 2021-12-22T00:00:00+00:00 [queued]>
[2025-06-18 16:15:51,075] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2025-06-18 16:15:51,075] {taskinstance.py:1043} INFO - Starting attempt 2 of 6
[2025-06-18 16:15:51,076] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2025-06-18 16:15:51,096] {taskinstance.py:1063} INFO - Executing <Task(PostgresOperator): insert_into_table> on 2021-12-22T00:00:00+00:00
[2025-06-18 16:15:51,101] {standard_task_runner.py:52} INFO - Started process 26781 to run task
[2025-06-18 16:15:51,105] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'connect_postgres_dag', 'insert_into_table', '2021-12-22T00:00:00+00:00', '--job-id', '13985', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/connect_postgres_dag.py', '--cfg-path', '/tmp/tmp0uclyijg', '--error-file', '/tmp/tmplaw93new']
[2025-06-18 16:15:51,109] {standard_task_runner.py:77} INFO - Job 13985: Subtask insert_into_table
[2025-06-18 16:15:51,172] {logging_mixin.py:104} INFO - Running <TaskInstance: connect_postgres_dag.insert_into_table 2021-12-22T00:00:00+00:00 [running]> on host 500dc4ac3a72
[2025-06-18 16:15:51,240] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=coder2j
AIRFLOW_CTX_DAG_ID=connect_postgres_dag
AIRFLOW_CTX_TASK_ID=insert_into_table
AIRFLOW_CTX_EXECUTION_DATE=2021-12-22T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-12-22T00:00:00+00:00
[2025-06-18 16:15:51,240] {postgres.py:69} INFO - Executing: 
            insert into employee (name,age,salary) values ('hayyye', '1997','5000.00');
        
[2025-06-18 16:15:51,251] {base.py:74} INFO - Using connection to: id: postgres_localhost. Host: postgres, Port: 5432, Schema: test, Login: airflow, Password: XXXXXXXX, extra: None
[2025-06-18 16:15:51,257] {dbapi.py:180} INFO - Running statement: 
            insert into employee (name,age,salary) values ('hayyye', '1997','5000.00');
        , parameters: None
[2025-06-18 16:15:51,258] {dbapi.py:186} INFO - Rows affected: 1
[2025-06-18 16:15:51,274] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=connect_postgres_dag, task_id=insert_into_table, execution_date=20211222T000000, start_date=20250618T161551, end_date=20250618T161551
[2025-06-18 16:15:51,311] {taskinstance.py:1220} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-18 16:15:51,318] {local_task_job.py:146} INFO - Task exited with return code 0
