[2025-06-18 16:25:26,034] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: connect_postgres_dag.insert_into_table 2024-12-24T00:00:00+00:00 [queued]>
[2025-06-18 16:25:26,057] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: connect_postgres_dag.insert_into_table 2024-12-24T00:00:00+00:00 [queued]>
[2025-06-18 16:25:26,058] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2025-06-18 16:25:26,058] {taskinstance.py:1043} INFO - Starting attempt 1 of 6
[2025-06-18 16:25:26,058] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2025-06-18 16:25:26,087] {taskinstance.py:1063} INFO - Executing <Task(PostgresOperator): insert_into_table> on 2024-12-24T00:00:00+00:00
[2025-06-18 16:25:26,091] {standard_task_runner.py:52} INFO - Started process 2657 to run task
[2025-06-18 16:25:26,099] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'connect_postgres_dag', 'insert_into_table', '2024-12-24T00:00:00+00:00', '--job-id', '16141', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/connect_postgres_dag.py', '--cfg-path', '/tmp/tmpikefzh6n', '--error-file', '/tmp/tmpa7sv4kzh']
[2025-06-18 16:25:26,103] {standard_task_runner.py:77} INFO - Job 16141: Subtask insert_into_table
[2025-06-18 16:25:26,241] {logging_mixin.py:104} INFO - Running <TaskInstance: connect_postgres_dag.insert_into_table 2024-12-24T00:00:00+00:00 [running]> on host ee91c01336f6
[2025-06-18 16:25:26,375] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=coder2j
AIRFLOW_CTX_DAG_ID=connect_postgres_dag
AIRFLOW_CTX_TASK_ID=insert_into_table
AIRFLOW_CTX_EXECUTION_DATE=2024-12-24T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-12-24T00:00:00+00:00
[2025-06-18 16:25:26,383] {postgres.py:69} INFO - Executing: 
            insert into employee (name,age,salary) values ('hayyye', '1997','5000.00');
        
[2025-06-18 16:25:26,403] {base.py:74} INFO - Using connection to: id: postgres_localhost. Host: postgres, Port: 5432, Schema: test, Login: airflow, Password: XXXXXXXX, extra: None
[2025-06-18 16:25:26,416] {dbapi.py:180} INFO - Running statement: 
            insert into employee (name,age,salary) values ('hayyye', '1997','5000.00');
        , parameters: None
[2025-06-18 16:25:26,417] {dbapi.py:186} INFO - Rows affected: 1
[2025-06-18 16:25:26,468] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=connect_postgres_dag, task_id=insert_into_table, execution_date=20241224T000000, start_date=20250618T162526, end_date=20250618T162526
[2025-06-18 16:25:26,596] {taskinstance.py:1220} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-18 16:25:26,615] {local_task_job.py:146} INFO - Task exited with return code 0
