[2025-06-18 15:09:10,526] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: first_dag.second_task 2025-02-05T00:00:00+00:00 [queued]>
[2025-06-18 15:09:10,577] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: first_dag.second_task 2025-02-05T00:00:00+00:00 [queued]>
[2025-06-18 15:09:10,579] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2025-06-18 15:09:10,584] {taskinstance.py:1043} INFO - Starting attempt 1 of 6
[2025-06-18 15:09:10,585] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2025-06-18 15:09:10,662] {taskinstance.py:1063} INFO - Executing <Task(BashOperator): second_task> on 2025-02-05T00:00:00+00:00
[2025-06-18 15:09:10,673] {standard_task_runner.py:52} INFO - Started process 15875 to run task
[2025-06-18 15:09:10,694] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'first_dag', 'second_task', '2025-02-05T00:00:00+00:00', '--job-id', '13520', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmp0c2qz1r8', '--error-file', '/tmp/tmpj5ywzff6']
[2025-06-18 15:09:10,704] {standard_task_runner.py:77} INFO - Job 13520: Subtask second_task
[2025-06-18 15:09:10,853] {logging_mixin.py:104} INFO - Running <TaskInstance: first_dag.second_task 2025-02-05T00:00:00+00:00 [running]> on host 500dc4ac3a72
[2025-06-18 15:09:11,041] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=my_name
AIRFLOW_CTX_DAG_ID=first_dag
AIRFLOW_CTX_TASK_ID=second_task
AIRFLOW_CTX_EXECUTION_DATE=2025-02-05T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2025-02-05T00:00:00+00:00
[2025-06-18 15:09:11,043] {bash.py:135} INFO - Tmp dir root location: 
 /tmp
[2025-06-18 15:09:11,046] {bash.py:158} INFO - Running command: echo "this is sencond task "
[2025-06-18 15:09:11,073] {bash.py:169} INFO - Output:
[2025-06-18 15:09:11,075] {bash.py:173} INFO - this is sencond task
[2025-06-18 15:09:11,075] {bash.py:177} INFO - Command exited with return code 0
[2025-06-18 15:09:11,189] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=first_dag, task_id=second_task, execution_date=20250205T000000, start_date=20250618T150910, end_date=20250618T150911
[2025-06-18 15:09:11,301] {taskinstance.py:1220} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-18 15:09:11,357] {local_task_job.py:146} INFO - Task exited with return code 0
