[2025-06-18 16:24:07,999] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: connect_postgres_dag.create_postgres_table 2024-01-30T00:00:00+00:00 [queued]>
[2025-06-18 16:24:08,026] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: connect_postgres_dag.create_postgres_table 2024-01-30T00:00:00+00:00 [queued]>
[2025-06-18 16:24:08,027] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2025-06-18 16:24:08,027] {taskinstance.py:1043} INFO - Starting attempt 1 of 6
[2025-06-18 16:24:08,027] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2025-06-18 16:24:08,069] {taskinstance.py:1063} INFO - Executing <Task(PostgresOperator): create_postgres_table> on 2024-01-30T00:00:00+00:00
[2025-06-18 16:24:08,079] {standard_task_runner.py:52} INFO - Started process 1144 to run task
[2025-06-18 16:24:08,085] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'connect_postgres_dag', 'create_postgres_table', '2024-01-30T00:00:00+00:00', '--job-id', '15474', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/connect_postgres_dag.py', '--cfg-path', '/tmp/tmp3x6_utej', '--error-file', '/tmp/tmpq7602l51']
[2025-06-18 16:24:08,089] {standard_task_runner.py:77} INFO - Job 15474: Subtask create_postgres_table
[2025-06-18 16:24:08,222] {logging_mixin.py:104} INFO - Running <TaskInstance: connect_postgres_dag.create_postgres_table 2024-01-30T00:00:00+00:00 [running]> on host ee91c01336f6
[2025-06-18 16:24:08,319] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=coder2j
AIRFLOW_CTX_DAG_ID=connect_postgres_dag
AIRFLOW_CTX_TASK_ID=create_postgres_table
AIRFLOW_CTX_EXECUTION_DATE=2024-01-30T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-01-30T00:00:00+00:00
[2025-06-18 16:24:08,320] {postgres.py:69} INFO - Executing: 
            create table if not exists employee (
                "name" text,
                "age" integer,
                "salary" numeric
            )
        
[2025-06-18 16:24:08,342] {base.py:74} INFO - Using connection to: id: postgres_localhost. Host: postgres, Port: 5432, Schema: test, Login: airflow, Password: XXXXXXXX, extra: None
[2025-06-18 16:24:08,349] {dbapi.py:180} INFO - Running statement: 
            create table if not exists employee (
                "name" text,
                "age" integer,
                "salary" numeric
            )
        , parameters: None
[2025-06-18 16:24:08,350] {dbapi.py:186} INFO - Rows affected: -1
[2025-06-18 16:24:08,350] {postgres.py:73} INFO - NOTICE:  relation "employee" already exists, skipping

[2025-06-18 16:24:08,377] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=connect_postgres_dag, task_id=create_postgres_table, execution_date=20240130T000000, start_date=20250618T162408, end_date=20250618T162408
[2025-06-18 16:24:08,542] {taskinstance.py:1220} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-18 16:24:08,589] {local_task_job.py:146} INFO - Task exited with return code 0
