[2025-06-18 15:00:23,922] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: first_dag.third_task 2021-10-12T00:00:00+00:00 [queued]>
[2025-06-18 15:00:23,963] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: first_dag.third_task 2021-10-12T00:00:00+00:00 [queued]>
[2025-06-18 15:00:23,964] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2025-06-18 15:00:23,964] {taskinstance.py:1043} INFO - Starting attempt 1 of 6
[2025-06-18 15:00:23,964] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2025-06-18 15:00:24,033] {taskinstance.py:1063} INFO - Executing <Task(BashOperator): third_task> on 2021-10-12T00:00:00+00:00
[2025-06-18 15:00:24,043] {standard_task_runner.py:52} INFO - Started process 3745 to run task
[2025-06-18 15:00:24,054] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'first_dag', 'third_task', '2021-10-12T00:00:00+00:00', '--job-id', '9885', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmpalddld82', '--error-file', '/tmp/tmpu2d5qpxx']
[2025-06-18 15:00:24,063] {standard_task_runner.py:77} INFO - Job 9885: Subtask third_task
[2025-06-18 15:00:24,250] {logging_mixin.py:104} INFO - Running <TaskInstance: first_dag.third_task 2021-10-12T00:00:00+00:00 [running]> on host 500dc4ac3a72
[2025-06-18 15:00:24,495] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=coder2j
AIRFLOW_CTX_DAG_ID=first_dag
AIRFLOW_CTX_TASK_ID=third_task
AIRFLOW_CTX_EXECUTION_DATE=2021-10-12T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-10-12T00:00:00+00:00
[2025-06-18 15:00:24,498] {bash.py:135} INFO - Tmp dir root location: 
 /tmp
[2025-06-18 15:00:24,507] {bash.py:158} INFO - Running command: echo "this is third task "
[2025-06-18 15:00:24,557] {bash.py:169} INFO - Output:
[2025-06-18 15:00:24,559] {bash.py:173} INFO - this is third task
[2025-06-18 15:00:24,560] {bash.py:177} INFO - Command exited with return code 0
[2025-06-18 15:00:24,697] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=first_dag, task_id=third_task, execution_date=20211012T000000, start_date=20250618T150023, end_date=20250618T150024
[2025-06-18 15:00:24,874] {taskinstance.py:1220} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-18 15:00:24,904] {local_task_job.py:146} INFO - Task exited with return code 0
