[2025-06-18 16:25:44,758] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: connect_postgres_dag.insert_into_table 2025-03-17T00:00:00+00:00 [queued]>
[2025-06-18 16:25:44,780] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: connect_postgres_dag.insert_into_table 2025-03-17T00:00:00+00:00 [queued]>
[2025-06-18 16:25:44,780] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2025-06-18 16:25:44,781] {taskinstance.py:1043} INFO - Starting attempt 1 of 6
[2025-06-18 16:25:44,781] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2025-06-18 16:25:44,830] {taskinstance.py:1063} INFO - Executing <Task(PostgresOperator): insert_into_table> on 2025-03-17T00:00:00+00:00
[2025-06-18 16:25:44,836] {standard_task_runner.py:52} INFO - Started process 3041 to run task
[2025-06-18 16:25:44,847] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'connect_postgres_dag', 'insert_into_table', '2025-03-17T00:00:00+00:00', '--job-id', '16307', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/connect_postgres_dag.py', '--cfg-path', '/tmp/tmpj1h33l1a', '--error-file', '/tmp/tmpwptqt0k5']
[2025-06-18 16:25:44,851] {standard_task_runner.py:77} INFO - Job 16307: Subtask insert_into_table
[2025-06-18 16:25:44,974] {logging_mixin.py:104} INFO - Running <TaskInstance: connect_postgres_dag.insert_into_table 2025-03-17T00:00:00+00:00 [running]> on host ee91c01336f6
[2025-06-18 16:25:45,066] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=coder2j
AIRFLOW_CTX_DAG_ID=connect_postgres_dag
AIRFLOW_CTX_TASK_ID=insert_into_table
AIRFLOW_CTX_EXECUTION_DATE=2025-03-17T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2025-03-17T00:00:00+00:00
[2025-06-18 16:25:45,067] {postgres.py:69} INFO - Executing: 
            insert into employee (name,age,salary) values ('hayyye', '1997','5000.00');
        
[2025-06-18 16:25:45,087] {base.py:74} INFO - Using connection to: id: postgres_localhost. Host: postgres, Port: 5432, Schema: test, Login: airflow, Password: XXXXXXXX, extra: None
[2025-06-18 16:25:45,096] {dbapi.py:180} INFO - Running statement: 
            insert into employee (name,age,salary) values ('hayyye', '1997','5000.00');
        , parameters: None
[2025-06-18 16:25:45,097] {dbapi.py:186} INFO - Rows affected: 1
[2025-06-18 16:25:45,130] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=connect_postgres_dag, task_id=insert_into_table, execution_date=20250317T000000, start_date=20250618T162544, end_date=20250618T162545
[2025-06-18 16:25:45,270] {taskinstance.py:1220} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-18 16:25:45,313] {local_task_job.py:146} INFO - Task exited with return code 0
