[2025-06-17 15:53:24,636] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: our_first_dag_v5.second_task 2022-11-03T00:00:00+00:00 [queued]>
[2025-06-17 15:53:24,724] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: our_first_dag_v5.second_task 2022-11-03T00:00:00+00:00 [queued]>
[2025-06-17 15:53:24,724] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2025-06-17 15:53:24,725] {taskinstance.py:1043} INFO - Starting attempt 1 of 6
[2025-06-17 15:53:24,725] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2025-06-17 15:53:24,789] {taskinstance.py:1063} INFO - Executing <Task(BashOperator): second_task> on 2022-11-03T00:00:00+00:00
[2025-06-17 15:53:24,819] {standard_task_runner.py:52} INFO - Started process 3128 to run task
[2025-06-17 15:53:24,842] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'our_first_dag_v5', 'second_task', '2022-11-03T00:00:00+00:00', '--job-id', '2816', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmpbcw0jwqb', '--error-file', '/tmp/tmp9v25xmdw']
[2025-06-17 15:53:24,854] {standard_task_runner.py:77} INFO - Job 2816: Subtask second_task
[2025-06-17 15:53:25,139] {logging_mixin.py:104} INFO - Running <TaskInstance: our_first_dag_v5.second_task 2022-11-03T00:00:00+00:00 [running]> on host 4f8b76136637
[2025-06-17 15:53:25,381] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=coder2j
AIRFLOW_CTX_DAG_ID=our_first_dag_v5
AIRFLOW_CTX_TASK_ID=second_task
AIRFLOW_CTX_EXECUTION_DATE=2022-11-03T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-03T00:00:00+00:00
[2025-06-17 15:53:25,382] {bash.py:135} INFO - Tmp dir root location: 
 /tmp
[2025-06-17 15:53:25,389] {bash.py:158} INFO - Running command: echo hey, I am task2 and will be running after task1!
[2025-06-17 15:53:25,419] {bash.py:169} INFO - Output:
[2025-06-17 15:53:25,421] {bash.py:173} INFO - hey, I am task2 and will be running after task1!
[2025-06-17 15:53:25,422] {bash.py:177} INFO - Command exited with return code 0
[2025-06-17 15:53:25,702] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=our_first_dag_v5, task_id=second_task, execution_date=20221103T000000, start_date=20250617T155324, end_date=20250617T155325
[2025-06-17 15:53:26,907] {taskinstance.py:1220} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-17 15:53:26,946] {local_task_job.py:146} INFO - Task exited with return code 0
