[2025-06-18 16:24:05,382] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: connect_postgres_dag.insert_into_table 2024-01-14T00:00:00+00:00 [queued]>
[2025-06-18 16:24:05,418] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: connect_postgres_dag.insert_into_table 2024-01-14T00:00:00+00:00 [queued]>
[2025-06-18 16:24:05,419] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2025-06-18 16:24:05,419] {taskinstance.py:1043} INFO - Starting attempt 1 of 6
[2025-06-18 16:24:05,419] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2025-06-18 16:24:05,450] {taskinstance.py:1063} INFO - Executing <Task(PostgresOperator): insert_into_table> on 2024-01-14T00:00:00+00:00
[2025-06-18 16:24:05,456] {standard_task_runner.py:52} INFO - Started process 1098 to run task
[2025-06-18 16:24:05,463] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'connect_postgres_dag', 'insert_into_table', '2024-01-14T00:00:00+00:00', '--job-id', '15451', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/connect_postgres_dag.py', '--cfg-path', '/tmp/tmpld4_kt38', '--error-file', '/tmp/tmp14fvwc_v']
[2025-06-18 16:24:05,467] {standard_task_runner.py:77} INFO - Job 15451: Subtask insert_into_table
[2025-06-18 16:24:05,550] {logging_mixin.py:104} INFO - Running <TaskInstance: connect_postgres_dag.insert_into_table 2024-01-14T00:00:00+00:00 [running]> on host ee91c01336f6
[2025-06-18 16:24:05,640] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=coder2j
AIRFLOW_CTX_DAG_ID=connect_postgres_dag
AIRFLOW_CTX_TASK_ID=insert_into_table
AIRFLOW_CTX_EXECUTION_DATE=2024-01-14T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-01-14T00:00:00+00:00
[2025-06-18 16:24:05,641] {postgres.py:69} INFO - Executing: 
            insert into employee (name,age,salary) values ('hayyye', '1997','5000.00');
        
[2025-06-18 16:24:05,664] {base.py:74} INFO - Using connection to: id: postgres_localhost. Host: postgres, Port: 5432, Schema: test, Login: airflow, Password: XXXXXXXX, extra: None
[2025-06-18 16:24:05,673] {dbapi.py:180} INFO - Running statement: 
            insert into employee (name,age,salary) values ('hayyye', '1997','5000.00');
        , parameters: None
[2025-06-18 16:24:05,674] {dbapi.py:186} INFO - Rows affected: 1
[2025-06-18 16:24:05,702] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=connect_postgres_dag, task_id=insert_into_table, execution_date=20240114T000000, start_date=20250618T162405, end_date=20250618T162405
[2025-06-18 16:24:05,814] {taskinstance.py:1220} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-18 16:24:05,847] {local_task_job.py:146} INFO - Task exited with return code 0
